# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/centrale-afzuiging/
# © Huizebruin.nl
substitutions:
  time_timezone: "Europe/Amsterdam"
  vdate: "v22.07.8"
  device_description: centrale afzuiging gemaakt door huizebruin.nl versie ${vdate} .
  friendly_name: centrale_afzuiging
  name: centrale_afzuiging
  
esphome:
  name: buva-afzuiging-zolder
  platform: ESP8266
  board: d1_mini
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"

dashboard_import:
  package_import_url: github://huizebruin/centrale-afzuiging/centrale-afzuiging-esp8266.yaml

wifi:
  ssid: !secret ssid
  password: !secret password


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}-Fallback"
    
web_server:
  port: 80
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

#  ⬇ Enable time component voor reset elke nacht ⬇ #
time:
  - platform: homeassistant
    id: time_homeassistant
    on_time_sync:
      - component.update: ${name}_uptime_timestamp

output:
  platform: esp8266_pwm
  pin: D5
  frequency: 2000 Hz
  id: pwm_output

fan:
  platform: speed
  output: pwm_output
  name: "Ventilation"
  speed_count:
    5
    
sensor:    
#------------------------#  sensoren #------------------------#
  - platform: uptime
    id: ${name}_uptime

  - platform: template
    id: ${name}_uptime_timestamp
    name: "${name} online sinds"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(${name}_uptime).state
      );
      return timestamp;  
      
  # WiFi signal
  - platform: wifi_signal
    name: "${name} - WiFi Signal"
    update_interval: 120s  
        
# ⬇ versie verbinding informatie sensoren voor in ha ⬇ #
  - platform: wifi_signal
    name: "${name} - WiFi Signal"
    update_interval: 120s
    
text_sensor:
  - platform: template
    name: "${name}_versie"
    id: ${name}_versie
    icon: "mdi:label-outline"
    update_interval: 6h
    lambda: |-
      return {"${vdate}"};
  - platform: wifi_info
    ip_address:
      name: IP-adres
      id: ${name}_ip_adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      id: ${name}_netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      id: ${name}_mac_adres
      icon: mdi:folder-key-network-outline

# ⬇ restart button voor de s0tool ⬇ #
button:  
  - platform: restart
    name: "Restart device"
