# Delen en bewerken mag maar laat deze eerste regels staan.
# Bron : https://www.huizebruin.nl
# Bron File : https://github.com/huizebruin/s0tool/tree/main/esphome
# © Huizebruin.nl
substitutions:
  vdate: "v22.06.1"
  device_description: centrale-afzuiging-gemaakt door huizebruin.nl versie ${vdate} .
  impulslengte: "50ms" #30ms of 50ms zie datasheet van het type meter
  name: variabele afzuiging

esphome:
  name: ${name}
  platform: ESP8266
  board: d1_mini
  comment: '${device_description}'
  project:
    name: huizebruin.${name}
    version: "${vdate}"
  
dashboard_import:
  package_import_url: github://huizebruin/centrale-afzuiging/centrale-afzuiging-esp8266.yaml@main

improv_serial:
  
wifi:
# secrets rechts boven binnen esphome (vanaf versie 2021.12.0 - 11th standaard in de secrets)
  # ssid: "wifi_ssid"
  # password: "wifi_password"
#------------------------##------------------------##------------------------##------------------------#
# ⬇ Hieronder niets veranderen tenzij je het overal goed aanpast ⬇ #
# ⬇ Schakel fallback-hotspot (captive portal) in voor het geval de wifi-verbinding mislukt ⬇ #
  ap:
    ssid: "${name}"

web_server:
  port: 80
  
captive_portal:
# ⬇ Enable logging ⬇ # 
logger:
  level: INFO
  
#  # ⬇ Enable Home Assistant API ⬇ # 
api:

ota:
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

#  ⬇ Enable time component voor reset elke nacht ⬇ #
time:
  - platform: homeassistant
    id: time_homeassistant

output:
  platform: esp8266_pwm
  pin: D5
  frequency: 2000 Hz
  id: pwm_output

fan:
  platform: speed
  output: pwm_output
  name: "Ventilation"
  speed_count:
    8

#------------------------#  sensoren #------------------------#
sensor:
# ⬇ versie verbinding informatie sensoren voor in ha ⬇ #
  - platform: wifi_signal
    name: "${name}_WiFi_Signal"
    update_interval: 120s
    
text_sensor:
  - platform: template
    name: "${name}_versie"
    id: ${name}_versie
    icon: "mdi:label-outline"
    update_interval: 6h
    lambda: |-
      return {"${vdate}"};

  - platform: wifi_info
    ip_address:
      name: IP-adres
      id: ${name}_ip_adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      id: ${name}_netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      id: ${name}_mac_adres
      icon: mdi:folder-key-network-outline

# ⬇ restart button voor de tool ⬇ #
button:  
  - platform: restart
    name: "Restart device"
