name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome/centrale-afzuiging-esp8266.yaml
      name: centrale-afzuiging
