---
name: Publish firmware

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish:
    name: "🛠️ ESPHome firmware"
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esphome/centrale-afzuiging-esp8266.yaml
      name: centrale-afzuiging
